FROM nginx

MAINTAINER Ivan Rybakov "rybakov39@gmail.com"

# add nginx conf
#ADD conf/nginx.conf /etc/nginx/conf.d/default.conf
COPY conf/nginx.conf /etc/nginx/nginx.conf
#COPY html/ /usr/share/nginx/html

# expose ports
EXPOSE 80

#WORKDIR /etc/nginx
#CMD ["nginx"]
